# используем язык java. Travis CI поддерживает разные языки.
language: java

# указываем текущую версию jdk: например openjdk8 или oraclejdk14
jdk: oraclejdk16

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo

# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -yarmail@yandex.ru
    on_success: never # default: change
    on_failure: never # default: always
